version: "3"
services:
  web:
    container_name: ProcerApp
    build: .
    image: node:18-alpine
    restart: unless-stopped
    working_dir: /usr/src/app
    command: sh -c "yarn install && yarn run dev"
    env_file: .env
    environment:
      NEXT_TELEMETRY_DISABLED: ${NEXT_TELEMETRY_DISABLED}
    volumes:
      - ./web:/usr/src/app
    ports:
      - "3000:3000"
    networks:
      - procer

networks: 
  procer:
    name: Procer
    driver: bridge
